apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx-femi
  name: nginx-femi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-femi
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-femi
    spec:
      containers:
      - image: httpd
        name: httpd
        resources: {}
status: {}
